#!/bin/bash

function set_ip_addresses() {
   check_ip_address

   export MYTESTIP_1=${CHECKED_IP_ADDRESS}
   export MYTESTIP_2='127.0.0.1'
   export MCAST_ADDR=$(echo ${CHECKED_IP_ADDRESS} | sed 's/^[0-9]*\./239./')
}

# checks IP address of a net device
# see the code logic for more info
# returns result in var $CHECKED_IP_ADDRESS
function check_ip_address() {
   DEFAULT_INTERFACE=$(netstat -rn | awk '{ if ($1 == "0.0.0.0") print $NF}')
   check_ip_address_on_dev ${DEFAULT_INTERFACE}
}

# checks IP address of the given dev, i.e. eth0, tun0 etc., and puts it to $CHECKED_IP_ADDRESS variable
# calling without any param it returns list of all ip address of each dev in systems delimited by space
function check_ip_address_on_dev() {
   dev_to_check=${1}
   CHECKED_IP_ADDRESS=$(/sbin/ifconfig $dev_to_check | awk '/inet/ {split ($2,A,":"); print A[2]}')
}

