#!/bin/bash

readonly JBOSSAS_SERVICE_NAME=${JBOSSAS_SERVICE_NAME:-'jboss-eap7'}
readonly HTTP_PROXY_SERVICE_NAME=${HTTP_PROXY_SERVICE_NAME:-'nginx'}

if [[ $EUID -ne 0 ]]; then
 echo "This script must be run as root"
 exit 1
fi

echo "Disbaling monitoring to avoid false+ alerts:"
monit unmonitor "${JBOSSAS_SERVICE_NAME}"
monit unmonitor "${HTTP_PROXY_SERVICE_NAME}"

echo "Restarting ${JBOSSAS_SERVICE_NAME}:"
monit restart jboss-eap7

echo "Enabling monitoring again"
monit monitor "${JBOSSAS_SERVICE_NAME}"
monit monitor "${HTTP_PROXY_SERVICE_NAME}"
